### ISSUE TITLE
Could not find stored procedure 'dbo.usp_sqlwatch_config_sqlserver_set_blocked_proc_threshold'.

### ISSUE THREAD

**Issue by francesco1119** [marcingminski/sql-performance-monitor#430]
**Did you check DOCS to make sure there is no workaround?**
YES

**Describe the bug**
In a fresh new installation of SQLWATCH, following this guide (https://docs.sqlwatch.io/configuration/basics/) if I run 

```
--default threshold will be 15 seconds:
exec [dbo].[usp_sqlwatch_config_sqlserver_set_blocked_proc_threshold] 
```

I receive the error: 

```
Msg 2812, Level 16, State 62, Line 2
Could not find stored procedure 'dbo.usp_sqlwatch_config_sqlserver_set_blocked_proc_threshold'.

Completion time: 2021-12-20T13:44:45.9039086+01:00
```

And is the same for all the rest of the queries. 
I'm running them on `master`

**To Reproduce**
1. Install SQLWATCH through `Install-DbaSqlWatch -SqlInstance localhost -Database SQLWATCH`
2. Install also `Install-DbaWhoIsActive -SqlInstance localhost -Database master`
3. Run on `master  `

```
--default threshold will be 15 seconds:
exec [dbo].[usp_sqlwatch_config_sqlserver_set_blocked_proc_threshold] 
```
and I receive the error:

```
Msg 2812, Level 16, State 62, Line 2
Could not find stored procedure 'dbo.usp_sqlwatch_config_sqlserver_set_blocked_proc_threshold'.

Completion time: 2021-12-20T13:44:45.9039086+01:00
```

**Expected behavior**
The query shoud execute without errors

**Screenshots**

**Windows Server (please complete the following information):**
 - OS Version: Windows 10 Enterprise

**SQL Server (please complete the following information):**
 - SQL Version: `Microsoft SQL Server 2019 (RTM-CU14) (KB5007182) - 15.0.4188.2 (X64)   Nov  3 2021 19:19:51   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Enterprise 10.0 <X64> (Build 19042: ) (Hypervisor) `
 
**SQL Server Management Studio (SSMS -> about -> copy info):**
 - paste "about" info here:
```
SQL Server Management Studio						15.0.18390.0
SQL Server Management Objects (SMO)						16.100.46521.71
Microsoft Analysis Services Client Tools						15.0.19714.0
Microsoft Data Access Components (MDAC)						10.0.19041.1
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.19042
```
 
**SQLWATCH version (from DACPAC or from sysinstances)**
 -  latest as per today
 
**Additional context**
I'm running this non `master`, should I run it on another DB?

**Comment by marcingminski** [comment]
Hi there,
What version are you using? the proc definitely exists: https://github.com/marcingminski/sqlwatch/blob/main/SqlWatch.Monitor/Project.SqlWatch.Database/dbo/Procedures/usp_sqlwatch_config_sqlserver_set_blocked_proc_threshold.sql

**Comment by francesco1119** [comment]
Yes, I found it. 
Thank you
